### ISSUE TITLE
Table too short

### ISSUE THREAD

**Issue by Mx74** [booya-at/freecad_glider#5]
In Edit Cell menu, while trying to setup the diagonal ribs and vector strap, the table length is way too short. 
For a traditional 4 lineer glider, with 3 main lines with 2 cascade, the minimum length should be 96 lines in the table. (24 diagonals ribs per row)

In cell_tool.py, increase the 2 table length, vector_table and diagonal_table line 70 and 126 to a sufficiant amount (200?) 

Or better, find a way to make these tables auto-expendable?

**Comment by looooo** [comment]
btw.: you can use multiple cells as input. So it's not necessary to use one line for one diagonal /vector strap.

**Comment by Mx74** [comment]
!! 
I didn't realized that. 
I should have think about it...

So yes, in that case 10 row might be enough. 

Another silly question, what do vector straps that you can't do with diagonals? 
Currently I find diagonals more convenient as you can't also create straps, but not only at the bottom surface but also at the top surface. 

![capture d ecran de 2018-04-03 17-34-42](https://user-images.githubusercontent.com/23337492/38259471-63c96a46-3765-11e8-928d-341808411a82.png)
